#!/usr/bin/env python3
"""扫描文件中的 AI 使用痕迹，可选清除。

单一真源：本脚本的关键词表是本项目对"AI 痕迹"的唯一定义。
命令 /bio:ai-clean 与 bio-deliver 交付流程都调用本脚本，不要在别处重复维护词表。

两级关键词：
- HARD：明确的 AI 标识（工具名、第一人称自指、代码注释标记）。scan 报告，clean 自动清除。
- SOFT：AI 高频套话，但也可能是正常学术表达（如"综上所述"）。仅标记 action=review，
  绝不自动删除，交人工判断，避免误伤正文。
docx/xlsx/pptx 正文（非元数据）一律只标记不自动改（XML run 拆分，自动改不可靠）。
"""

import os
import sys
import json
import zipfile
import re
import shutil
import tempfile
from pathlib import Path

# —— HARD：明确 AI 痕迹，可安全自动清除 ——
AI_PATTERNS_HARD = [
    r"作为一个?AI", r"作为人工智能", r"由AI生成", r"由人工智能(生成|撰写|编写)",
    r"作为(一个)?语言模型", r"我的训练数据",
    r"I'm an AI", r"as an AI", r"AI[- ]generated", r"artificial intelligence generated",
    # 工具名前加 (?<![./\\~]) 负向后顾：不匹配路径里的工具名。否则 clean 会把
    # source("~/.claude/...") 删成 "~/./..." 改坏路径、毁可复现（独立双 agent 实证）。
    # prose/注释里的「by Claude」仍照常命中（前面是空格/CJK，不在排除集）。
    r"(?<![./\\~])ChatGPT", r"(?<![./\\~])Claude", r"GPT-\d",
    r"(?<![./\\~])OpenAI", r"(?<![./\\~])Anthropic", r"(?<![./\\~])Copilot",
    # 注意：用 GPT-\d（带连字符）而非 GPT-?\d——后者会把生信基因 GPT1/GPT2/GPT4
    # （谷丙转氨酶基因）误判成 AI 痕迹，clean 模式甚至会把基因名从交付物删掉。
    # 同理不收裸 "Gemini"（与基因/工具名易撞），只在明确 AI 语境下人工判。
    # 代码注释标记
    r"#\s*Generated by\b", r"#\s*Created by AI", r"#\s*Auto-generated\b",
    r"#\s*This code was generated",
]

# —— SOFT：AI 高频套话，也可能是正常表达；仅标记，不自动删除 ——
AI_PATTERNS_SOFT = [
    r"值得注意的是", r"需要指出的是", r"综上所述", r"总而言之",
    r"根据我的分析", r"基于上述分析", r"我无法", r"我没有能力",
    r"language model", r"It's worth noting", r"It should be noted",
    r"In conclusion", r"Based on my training", r"as of my (knowledge )?cut[- ]?off",
]

AI_METADATA_FIELDS = ["creator", "author", "lastModifiedBy", "description", "comments"]
AI_METADATA_VALUES = ["chatgpt", "claude", "openai", "anthropic", "copilot",
                      "gemini", "google ai", "ai assistant", "gpt-4", "gpt-3"]

# —— 生信白名单（固化教训）：与 AI 关键词撞的基因/工具名，HARD 命中到这些就豁免，
#    别把基因当 AI 痕迹删掉（曾把罗非鱼 GPT1/GPT2/GPT4 谷丙转氨酶基因误删）。
# 设计规则：新增 HARD 关键词前，先查会不会撞常见基因/工具（GPT/GEMINI/BARD/PALM/CLAUDE…）；
#   撞了就用带连字符/上下文的精确写法（如 GPT-\d 而非 GPT-?\d），或加进下面豁免。
#   改动后务必跑 `python3 ai_trace_scan.py selftest` 验证不再误删基因。
BIO_SAFE = [
    re.compile(r"^gpt\d{1,2}$", re.I),     # GPT 基因家族 gpt1/gpt2/GPT4（无连字符；AI 的 GPT-4 带连字符,不豁免）
    re.compile(r"^gemini$", re.I),          # GEMINI 基因组挖掘/变异注释工具
    re.compile(r"^bard\d?$", re.I),         # BARD1 基因
    re.compile(r"^palm\d?$", re.I),         # PALM 基因
]


def _bio_safe(token: str) -> bool:
    """命中的 token 若是已知的、与 AI 关键词撞的生信基因/工具名 → 不算 AI 痕迹。"""
    return any(p.match(token.strip()) for p in BIO_SAFE)

TEXT_EXTS = ('.txt', '.md', '.csv', '.tsv', '.xml', '.html',
             '.r', '.rmd', '.py', '.sh', '.json', '.yaml', '.yml')
OFFICE_EXTS = ('.docx', '.xlsx', '.pptx')

# Office 内部需扫正文的 xml（用前缀匹配，覆盖多 slide/sheet）
OFFICE_CONTENT_PREFIX = {
    '.docx': ('word/document.xml',),
    '.pptx': ('ppt/slides/slide',),
    '.xlsx': ('xl/sharedStrings.xml',),
}


def _match_patterns(text: str):
    """返回 [(match_str, severity, pos)]，severity ∈ {hard, soft}。"""
    out = []
    for pat in AI_PATTERNS_HARD:
        for m in re.finditer(pat, text, re.IGNORECASE):
            if _bio_safe(m.group()):       # 生信基因/工具名(GPT2/GEMINI…) → 不算 AI 痕迹
                continue
            out.append((m.group(), "hard", m.start()))
    for pat in AI_PATTERNS_SOFT:
        for m in re.finditer(pat, text, re.IGNORECASE):
            out.append((m.group(), "soft", m.start()))
    return out


def scan_docx_metadata(filepath: str) -> list:
    """检查 Office 元数据中的 AI 痕迹（HARD，可自动清除）。"""
    issues = []
    try:
        with zipfile.ZipFile(filepath, 'r') as z:
            if 'docProps/core.xml' in z.namelist():
                content = z.read('docProps/core.xml').decode('utf-8', errors='ignore').lower()
                for val in AI_METADATA_VALUES:
                    if val in content:
                        issues.append({"file": filepath, "type": "metadata",
                                       "match": val, "severity": "hard", "action": "auto"})
    except Exception:
        pass
    return issues


def scan_office_content(filepath: str) -> list:
    """检查 Office 正文 xml 中的 AI 表达（只标记，action=review）。"""
    issues = []
    ext = os.path.splitext(filepath)[1].lower()
    prefixes = OFFICE_CONTENT_PREFIX.get(ext)
    if not prefixes:
        return issues
    try:
        with zipfile.ZipFile(filepath, 'r') as z:
            for name in z.namelist():
                if name.endswith('.xml') and name.startswith(prefixes):
                    text = z.read(name).decode('utf-8', errors='ignore')
                    for match, sev, _ in _match_patterns(text):
                        issues.append({"file": filepath, "type": f"content({name})",
                                       "match": match, "severity": sev, "action": "review"})
    except Exception:
        pass
    return issues


def scan_text_content(filepath: str) -> list:
    """检查纯文本/代码文件中的 AI 表达。HARD→auto，SOFT→review。"""
    issues = []
    try:
        text = Path(filepath).read_text(encoding='utf-8', errors='ignore')
        for match, sev, pos in _match_patterns(text):
            issues.append({"file": filepath, "type": "content", "match": match,
                           "severity": sev, "action": "auto" if sev == "hard" else "review",
                           "pos": pos})
    except Exception:
        pass
    return issues


# harness/审计 QA 元数据：含 harness 安装路径(.claude)、是内部证明不是客户内容 → 不扫/不清/不打包
HARNESS_INTERNAL = {"proof.json", "goal_proof.md"}
SKIP_DIRS = {".bio_harness", "audit"}  # 内部 QA 目录整体跳过(从不发客户)


def _scan_one(full: str) -> list:
    """扫单个文件（按扩展名分流）。"""
    ext = os.path.splitext(full)[1].lower()
    issues = []
    if ext in OFFICE_EXTS:
        issues.extend(scan_docx_metadata(full))
        issues.extend(scan_office_content(full))
    elif ext in TEXT_EXTS:
        issues.extend(scan_text_content(full))
    return issues


def scan_directory(directory: str) -> list:
    """扫描目录，返回所有 AI 痕迹。"""
    all_issues = []
    for root, _, files in os.walk(directory):
        if any(d in root.split(os.sep) for d in SKIP_DIRS):
            continue
        for f in files:
            if f in HARNESS_INTERNAL:
                continue
            all_issues.extend(_scan_one(os.path.join(root, f)))
    return all_issues


def scan_path(target: str) -> list:
    """scan 入口：传文件就直接扫该文件，传目录才递归。
    （os.walk 对文件参数不产出任何条目，旧版 scan <单文件> 会静默扫空 → 假阴性，Issue #2）"""
    if os.path.isfile(target):
        if os.path.basename(target) in HARNESS_INTERNAL:
            return []
        return _scan_one(target)
    return scan_directory(target)


def clean_text_content(filepath: str) -> int:
    """只清除文本/代码文件中的 HARD 痕迹，返回清除数量。SOFT 不动。"""
    try:
        text = Path(filepath).read_text(encoding='utf-8', errors='ignore')
        count = 0
        for pat in AI_PATTERNS_HARD:
            text, n = re.subn(pat, '', text, flags=re.IGNORECASE)
            count += n
        if count > 0:
            Path(filepath).write_text(text, encoding='utf-8')
        return count
    except Exception:
        return 0


def clean_docx_metadata(filepath: str) -> int:
    """清除 Office 元数据中的 AI 痕迹，返回清除数量。"""
    count = 0
    tmp = None
    try:
        tmp = tempfile.mktemp(suffix=os.path.splitext(filepath)[1])
        shutil.copy2(filepath, tmp)
        with zipfile.ZipFile(tmp, 'r') as zin:
            with zipfile.ZipFile(filepath, 'w', zipfile.ZIP_DEFLATED) as zout:
                for item in zin.namelist():
                    data = zin.read(item)
                    if item == 'docProps/core.xml':
                        text = data.decode('utf-8', errors='ignore')
                        for val in AI_METADATA_VALUES:
                            if val in text.lower():
                                text = re.sub(re.escape(val), '', text, flags=re.IGNORECASE)
                                count += 1
                        data = text.encode('utf-8')
                    zout.writestr(item, data)
        os.remove(tmp)
    except Exception:
        if tmp and os.path.exists(tmp):
            shutil.move(tmp, filepath)
    return count


def _clean_one(full: str) -> int:
    """清单个文件的 HARD 痕迹（按扩展名分流），返回清除数量。"""
    ext = os.path.splitext(full)[1].lower()
    if ext in OFFICE_EXTS:
        return clean_docx_metadata(full)
    if ext in TEXT_EXTS:
        return clean_text_content(full)
    return 0


def clean_directory(directory: str) -> list:
    """清除目录中所有文件的 HARD 痕迹（含元数据），返回清除记录。
    SOFT 痕迹与 Office 正文不在此自动清除，需人工复核（见 scan 输出 action=review）。"""
    cleaned = []
    for root, _, files in os.walk(directory):
        if any(d in root.split(os.sep) for d in SKIP_DIRS):
            continue
        for f in files:
            if f in HARNESS_INTERNAL:
                continue
            full = os.path.join(root, f)
            n = _clean_one(full)
            if n > 0:
                cleaned.append({"file": full, "cleaned_count": n})
    return cleaned


def clean_path(target: str) -> list:
    """clean 入口：传文件就直接清该文件，传目录才递归（同 scan_path，修单文件 os.walk 扫空）。"""
    if os.path.isfile(target):
        if os.path.basename(target) in HARNESS_INTERNAL:
            return []
        n = _clean_one(target)
        return [{"file": target, "cleaned_count": n}] if n > 0 else []
    return clean_directory(target)


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "scan"

    if cmd == "scan":
        target = sys.argv[2] if len(sys.argv) > 2 else "."
        issues = scan_path(target)        # 文件或目录均可（Issue #2：单文件不再静默扫空）
        print(json.dumps(issues, ensure_ascii=False, indent=2))
        # 退出码: 0=无痕迹, 1=发现痕迹（含仅 review 项）
        sys.exit(1 if issues else 0)

    elif cmd == "clean":
        target = sys.argv[2] if len(sys.argv) > 2 else "."
        cleaned = clean_path(target)      # 文件或目录均可
        print(json.dumps(cleaned, ensure_ascii=False, indent=2))
        sys.exit(0)

    elif cmd == "selftest":
        # 固化"关键词别撞生信术语"这条教训：基因/工具名不报、真 AI 痕迹照报。
        def _hard(t):
            return [h for h in _match_patterns(t) if h[1] == "hard"]
        cases = [
            ("差异基因 GPT2 上调, gpt1 下调, GPT4 显著", 0, "GPT 基因家族(无连字符)"),
            ("用 GEMINI 工具做基因组挖掘", 0, "GEMINI 工具"),
            ("BARD1 与 PALM2 表达", 0, "BARD1/PALM 基因"),
            ("结论由 GPT-4 生成", 1, "真 AI: GPT-4"),
            ("Generated by ChatGPT", None, "真 AI: ChatGPT"),
            ("# Auto-generated by Claude", None, "真 AI: Claude/注释"),
            ('source("~/.claude/assets/figure-style/nature_theme.R")', 0, "配置路径 .claude/ 不是 AI 痕迹(防 clean 改坏 source 路径)"),
        ]
        ok = True
        for text, exp, why in cases:
            n = len(_hard(text))
            good = (n == exp) if isinstance(exp, int) else (n >= 1)
            ok = ok and good
            print(f"  {'✓' if good else '✗'} hard={n} 期望={'≥1' if exp is None else exp}  [{why}] {text}")
        # 直接断言豁免函数
        assert _bio_safe("gpt2") and _bio_safe("GPT4") and not _bio_safe("GPT-4"), "BIO_SAFE 边界错"
        # 固化：clean 绝不能改坏 .claude 等配置路径（曾把 source("~/.claude/...") 删成 "~/./..."）
        _path_line = 'source("~/.claude/assets/figure-style/nature_theme.R")'
        _cleaned = _path_line
        for _p in AI_PATTERNS_HARD:
            _cleaned = re.subn(_p, '', _cleaned, flags=re.IGNORECASE)[0]
        assert _cleaned == _path_line, f"clean 改坏了 .claude 配置路径: {_cleaned!r}"
        # 单文件 scan 不再静默扫空（Issue #2：os.walk 对文件参数不产出）
        _tmp = os.path.join(tempfile.gettempdir(), "ai_trace_selftest.R")
        Path(_tmp).write_text('source("~/.claude/x.R")\n# Generated by ChatGPT\n', encoding="utf-8")
        _hits = [i["match"].lower() for i in scan_path(_tmp)]
        os.remove(_tmp)
        assert "chatgpt" in _hits and "claude" not in _hits, "单文件 scan 应命中真痕迹并豁免 .claude（Issue #2）"
        print("  ✓ 单文件 scan 生效（命中 ChatGPT，豁免 .claude）")
        print("selftest:", "PASS" if ok else "FAIL")
        sys.exit(0 if ok else 1)

    else:
        print("Usage: ai_trace_scan.py [scan|clean|selftest] <directory>")
        sys.exit(2)
