#!/usr/bin/env python3
"""扫描文件中的 AI 使用痕迹，可选清除。

单一真源：本脚本的关键词表是本项目对"AI 痕迹"的唯一定义。
命令 /bio:ai-clean 与 bio-deliver 交付流程都调用本脚本，不要在别处重复维护词表。

两级关键词：
- HARD：明确的 AI 标识（工具名、第一人称自指、代码注释标记）。scan 报告，clean 自动清除。
- SOFT：AI 高频套话，但也可能是正常学术表达（如"综上所述"）。仅标记 action=review，
  绝不自动删除，交人工判断，避免误伤正文。
docx/xlsx/pptx 正文（非元数据）一律只标记不自动改（XML run 拆分，自动改不可靠）。
"""

import os
import sys
import json
import zipfile
import re
import shutil
import tempfile
from pathlib import Path

# —— HARD：明确 AI 痕迹，可安全自动清除 ——
AI_PATTERNS_HARD = [
    r"作为一个?AI", r"作为人工智能", r"由AI生成", r"由人工智能(生成|撰写|编写)",
    r"作为(一个)?语言模型", r"我的训练数据",
    r"I'm an AI", r"as an AI", r"AI[- ]generated", r"artificial intelligence generated",
    r"ChatGPT", r"Claude", r"GPT-?\d", r"OpenAI", r"Anthropic", r"Copilot", r"Gemini",
    # 代码注释标记
    r"#\s*Generated by\b", r"#\s*Created by AI", r"#\s*Auto-generated\b",
    r"#\s*This code was generated",
]

# —— SOFT：AI 高频套话，也可能是正常表达；仅标记，不自动删除 ——
AI_PATTERNS_SOFT = [
    r"值得注意的是", r"需要指出的是", r"综上所述", r"总而言之",
    r"根据我的分析", r"基于上述分析", r"我无法", r"我没有能力",
    r"language model", r"It's worth noting", r"It should be noted",
    r"In conclusion", r"Based on my training", r"as of my (knowledge )?cut[- ]?off",
]

AI_METADATA_FIELDS = ["creator", "author", "lastModifiedBy", "description", "comments"]
AI_METADATA_VALUES = ["chatgpt", "claude", "openai", "anthropic", "copilot",
                      "gemini", "google ai", "ai assistant", "gpt-4", "gpt-3"]

TEXT_EXTS = ('.txt', '.md', '.csv', '.tsv', '.xml', '.html',
             '.r', '.rmd', '.py', '.sh', '.json', '.yaml', '.yml')
OFFICE_EXTS = ('.docx', '.xlsx', '.pptx')

# Office 内部需扫正文的 xml（用前缀匹配，覆盖多 slide/sheet）
OFFICE_CONTENT_PREFIX = {
    '.docx': ('word/document.xml',),
    '.pptx': ('ppt/slides/slide',),
    '.xlsx': ('xl/sharedStrings.xml',),
}


def _match_patterns(text: str):
    """返回 [(match_str, severity, pos)]，severity ∈ {hard, soft}。"""
    out = []
    for pat in AI_PATTERNS_HARD:
        for m in re.finditer(pat, text, re.IGNORECASE):
            out.append((m.group(), "hard", m.start()))
    for pat in AI_PATTERNS_SOFT:
        for m in re.finditer(pat, text, re.IGNORECASE):
            out.append((m.group(), "soft", m.start()))
    return out


def scan_docx_metadata(filepath: str) -> list:
    """检查 Office 元数据中的 AI 痕迹（HARD，可自动清除）。"""
    issues = []
    try:
        with zipfile.ZipFile(filepath, 'r') as z:
            if 'docProps/core.xml' in z.namelist():
                content = z.read('docProps/core.xml').decode('utf-8', errors='ignore').lower()
                for val in AI_METADATA_VALUES:
                    if val in content:
                        issues.append({"file": filepath, "type": "metadata",
                                       "match": val, "severity": "hard", "action": "auto"})
    except Exception:
        pass
    return issues


def scan_office_content(filepath: str) -> list:
    """检查 Office 正文 xml 中的 AI 表达（只标记，action=review）。"""
    issues = []
    ext = os.path.splitext(filepath)[1].lower()
    prefixes = OFFICE_CONTENT_PREFIX.get(ext)
    if not prefixes:
        return issues
    try:
        with zipfile.ZipFile(filepath, 'r') as z:
            for name in z.namelist():
                if name.endswith('.xml') and name.startswith(prefixes):
                    text = z.read(name).decode('utf-8', errors='ignore')
                    for match, sev, _ in _match_patterns(text):
                        issues.append({"file": filepath, "type": f"content({name})",
                                       "match": match, "severity": sev, "action": "review"})
    except Exception:
        pass
    return issues


def scan_text_content(filepath: str) -> list:
    """检查纯文本/代码文件中的 AI 表达。HARD→auto，SOFT→review。"""
    issues = []
    try:
        text = Path(filepath).read_text(encoding='utf-8', errors='ignore')
        for match, sev, pos in _match_patterns(text):
            issues.append({"file": filepath, "type": "content", "match": match,
                           "severity": sev, "action": "auto" if sev == "hard" else "review",
                           "pos": pos})
    except Exception:
        pass
    return issues


# harness/审计 QA 元数据：含 harness 安装路径(.claude)、是内部证明不是客户内容 → 不扫/不清/不打包
HARNESS_INTERNAL = {"proof.json", "goal_proof.md"}
SKIP_DIRS = {".bio_harness", "audit"}  # 内部 QA 目录整体跳过(从不发客户)


def scan_directory(directory: str) -> list:
    """扫描目录，返回所有 AI 痕迹。"""
    all_issues = []
    for root, _, files in os.walk(directory):
        if any(d in root.split(os.sep) for d in SKIP_DIRS):
            continue
        for f in files:
            if f in HARNESS_INTERNAL:
                continue
            full = os.path.join(root, f)
            ext = os.path.splitext(f)[1].lower()
            if ext in OFFICE_EXTS:
                all_issues.extend(scan_docx_metadata(full))
                all_issues.extend(scan_office_content(full))
            elif ext in TEXT_EXTS:
                all_issues.extend(scan_text_content(full))
    return all_issues


def clean_text_content(filepath: str) -> int:
    """只清除文本/代码文件中的 HARD 痕迹，返回清除数量。SOFT 不动。"""
    try:
        text = Path(filepath).read_text(encoding='utf-8', errors='ignore')
        count = 0
        for pat in AI_PATTERNS_HARD:
            text, n = re.subn(pat, '', text, flags=re.IGNORECASE)
            count += n
        if count > 0:
            Path(filepath).write_text(text, encoding='utf-8')
        return count
    except Exception:
        return 0


def clean_docx_metadata(filepath: str) -> int:
    """清除 Office 元数据中的 AI 痕迹，返回清除数量。"""
    count = 0
    tmp = None
    try:
        tmp = tempfile.mktemp(suffix=os.path.splitext(filepath)[1])
        shutil.copy2(filepath, tmp)
        with zipfile.ZipFile(tmp, 'r') as zin:
            with zipfile.ZipFile(filepath, 'w', zipfile.ZIP_DEFLATED) as zout:
                for item in zin.namelist():
                    data = zin.read(item)
                    if item == 'docProps/core.xml':
                        text = data.decode('utf-8', errors='ignore')
                        for val in AI_METADATA_VALUES:
                            if val in text.lower():
                                text = re.sub(re.escape(val), '', text, flags=re.IGNORECASE)
                                count += 1
                        data = text.encode('utf-8')
                    zout.writestr(item, data)
        os.remove(tmp)
    except Exception:
        if tmp and os.path.exists(tmp):
            shutil.move(tmp, filepath)
    return count


def clean_directory(directory: str) -> list:
    """清除目录中所有文件的 HARD 痕迹（含元数据），返回清除记录。
    SOFT 痕迹与 Office 正文不在此自动清除，需人工复核（见 scan 输出 action=review）。"""
    cleaned = []
    for root, _, files in os.walk(directory):
        if any(d in root.split(os.sep) for d in SKIP_DIRS):
            continue
        for f in files:
            if f in HARNESS_INTERNAL:
                continue
            full = os.path.join(root, f)
            ext = os.path.splitext(f)[1].lower()
            n = 0
            if ext in OFFICE_EXTS:
                n += clean_docx_metadata(full)
            elif ext in TEXT_EXTS:
                n += clean_text_content(full)
            if n > 0:
                cleaned.append({"file": full, "cleaned_count": n})
    return cleaned


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "scan"

    if cmd == "scan":
        target = sys.argv[2] if len(sys.argv) > 2 else "."
        issues = scan_directory(target)
        print(json.dumps(issues, ensure_ascii=False, indent=2))
        # 退出码: 0=无痕迹, 1=发现痕迹（含仅 review 项）
        sys.exit(1 if issues else 0)

    elif cmd == "clean":
        target = sys.argv[2] if len(sys.argv) > 2 else "."
        cleaned = clean_directory(target)
        print(json.dumps(cleaned, ensure_ascii=False, indent=2))
        sys.exit(0)

    else:
        print("Usage: ai_trace_scan.py [scan|clean] <directory>")
        sys.exit(2)
